### ISSUE TITLE
Platform not supported

### ISSUE THREAD

**Issue by ipetinate** [daxter-army/key-cast#8]
## Descrition

I have trouble when install on my distro, maybe does not work on Wayland.

## Error

```
Traceback (most recent call last):
  File "keycast_prod.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[202619] Failed to execute script 'keycast_prod' due to unhandled exception!
```

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad T14 Gen 3
- **Memory:**                                      24.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i7-1270P × 16
- **Graphics:**                                    Intel® Graphics (ADL GT2)
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            N3MET18W (1.17 )
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.5-200.fc39.x86_64

**Comment by RafaelLinux** [comment]
I executed it from terminal but despite it's apparently loaded in memory, nothing appears in screen. No errors, but no signals of doing nothing. In fact, when I press Ctrl+C after launch it in terminal to stop it, it takes near 1 minute to stop with this messages:
```
./keycast_prod 
^CTraceback (most recent call last):
  File "keycast_prod.py", line 392, in <module>
  File "tkinter/__init__.py", line 1429, in mainloop
KeyboardInterrupt
[29064] Failed to execute script 'keycast_prod' due to unhandled exception!
```

I'm using Wayland protocol, under Plasma in openSUSE
